Kwoc 2023 report
kossiitkgp/bolg pull request #6
Opened 2024-06-12 10:45 UTC by tejasexpress

2024-06-12 15:45 UTC, harshkhandeparkar requested changes

2024-06-12 15:45 UTC, harshkhandeparkar commented on blog/2024-06-12-kwoc-annual-report-2023.md
> +  - koss
The tags need to be added to the tags.yml file.

2024-06-12 15:45 UTC, harshkhandeparkar commented on blog/2024-06-12-kwoc-annual-report-2023.md
> +title: KWoC Annual Report 2023
Please add author.

2024-06-12 15:45 UTC, harshkhandeparkar commented on blog/2024-06-12-kwoc-annual-report-2023.md
> +---
Can rename it to KWoC 2023 Report

2024-06-12 15:45 UTC, harshkhandeparkar commented on blog/2024-06-12-kwoc-annual-report-2023.md
> +KWoC's main aim is to provide students with one-on-one mentorship as they take their first steps into the world of open source. It helps build bridges between budding developers and experienced mento
I don't think we should write one on one mentorship - we don't really expect that from mentors.

2024-06-18 19:04 UTC, tejasexpress commented on blog/2024-06-12-kwoc-annual-report-2023.md
> +title: KWoC Annual Report 2023
added

2024-06-18 19:04 UTC, tejasexpress commented on blog/2024-06-12-kwoc-annual-report-2023.md
> +---
changed

2024-06-18 19:04 UTC, tejasexpress commented on blog/2024-06-12-kwoc-annual-report-2023.md
> +KWoC's main aim is to provide students with one-on-one mentorship as they take their first steps into the world of open source. It helps build bridges between budding developers and experienced mento
changed

2024-06-18 19:05 UTC, harshkhandeparkar commented on blog/2024-06-12-kwoc-annual-report-2023.md
> +  - KOSS
I don't think there is any need to have a tag named "KOSS" but a KWoC tag would be good, we will probably make more KWoC blogs in the future.

2024-06-18 19:07 UTC, harshkhandeparkar commented on blog/2024-06-12-kwoc-annual-report-2023.md
> +  - KOSS
Ok the KOSS tag exists so let's keep it but add a KWoC tag.

2024-06-18 19:09 UTC, harshkhandeparkar commented on blog/2024-06-12-kwoc-annual-report-2023.md
> +  - KOSS
While you're at it, add the tag to the other KWoC blog too.

2024-06-18 19:17 UTC, harshkhandeparkar commented on blog/tags.yml
> +  description: bolgs related to Kharagpur Winter of Code
`B` in `Bolgs` can be capital.

2024-06-18 19:56 UTC, tejasexpress commented on blog/tags.yml
> +  description: bolgs related to Kharagpur Winter of Code
changd

2024-06-19 11:36 UTC, harshkhandeparkar approved these changes

2024-06-19 11:37 UTC, merged

2024-06-19 11:37 UTC, harshkhandeparkar commented
Thanks!